- name: download ESXi patches using custom ansible module
  hosts: localhost
  gather_facts: false
  tasks:
  - name: Run custom ESXi patch download module
    download_ESXi_patches:
      date: "05/21/2024"
      release: "{{ item }}"
      path: "/root/patching/downloads"
      cookie_file: "./cookies.txt"
    loop:
      - "7.0"
      - "8.0"
    register: result

  - name: print result
    debug:
      msg: '{{ result }}'
