---
- name: Update vCenter Server to latest patch
  hosts: localhost
  gather_facts: no
  vars:
    vcsa_url: "https://your-vcenter-server.com"
    vcsa_username: "administrator@vsphere.local"
    vcsa_password: "your_password"

  tasks:
    - name: Check current vCenter version
      vmware.vmware_rest.vcsa_system_info:
        hostname: "{{ vcsa_url }}"
        username: "{{ vcsa_username }}"
        password: "{{ vcsa_password }}"
        validate_certs: no
      register: current_version

    - name: Display current version
      debug:
        msg: "Current version: {{ current_version.system.version }}"
